### PR TITLE
fix Ubuntu packaging bugs

### PR DESCRIPTION
**Pull request by darealshinji**
These are Lintian's reports of the binary and source packages from the PPA:

```
W: simplescreenrecorder source: native-package-with-dash-version
E: simplescreenrecorder source: build-depends-on-build-essential build-depends
W: simplescreenrecorder source: ancient-standards-version 3.9.2 (current is 3.9.5)

W: simplescreenrecorder-lib: package-name-doesnt-match-sonames libssr-glinject
W: simplescreenrecorder-lib: description-synopsis-starts-with-article
W: simplescreenrecorder-lib: extended-description-line-too-long
E: simplescreenrecorder-lib: non-empty-dependency_libs-in-la-file usr/lib/x86_64-linux-gnu/libssr-glinject.la
W: simplescreenrecorder-lib: shlib-without-versioned-soname usr/lib/x86_64-linux-gnu/libssr-glinject.so libssr-glinject.so
E: simplescreenrecorder-lib: pkg-has-shlibs-control-file-but-no-actual-shared-libs

W: simplescreenrecorder: description-synopsis-starts-with-article
W: simplescreenrecorder: extended-description-line-too-long
W: simplescreenrecorder: binary-without-manpage usr/bin/simplescreenrecorder
W: simplescreenrecorder: binary-without-manpage usr/bin/ssr-glinject
W: simplescreenrecorder: maintainer-script-empty postinst
```

These changes will fix almost all of it.

The following warning is still remaining: `W: libssr-glinject: shlib-without-versioned-soname usr/lib/x86_64-linux-gnu/libssr-glinject.so libssr-glinject.so`
You should either consider building a library with a versioned soname or override the warning if you have a good reason for not versioning the soname.

This error is overridden because it's a bug in Lintian: `E: simplescreenrecorder-lib: pkg-has-shlibs-control-file-but-no-actual-shared-libs`

Other changes:
- Both binary packages are build from the same source package
- Upstream changelog (CHANGELOG.md) and additional doc files (AUTHORS.md notes.txt README.md todo.txt) will be installed
- simplescreenrecorder-lib was renamed to libssr-glinject to match the actual library name, but simplescreenrecorder-lib is still provided as a virtual package

### CODE REVIEW

**Comment by MaartenBaert** [comment]
libssr-glinject should not be versioned since it is tied to the simplescreenrecorder binary rather than the programs that will load it. That's also the reason why the package name is not 'libssr-glinject': it isn't a library in the traditional sense. The flash player package isn't called 'libflashplayer' either, even though that's the file name of the actual flash binary. I agree that the name 'simplescreenrecorder-lib' is badly chosen, it should probably be 'simplescreenrecorder-glinject', but changing that now will create confusion and require transitional packages, so I don't think it's worth it.

By the way, these package files need to be compatible with older versions down to Ubuntu 12.04, not just the latest release. Have you verified that the new format is also supported by 12.04?

Other than that it looks good, but you've made it hard for me to review this because it's all one big commit.

**Comment by darealshinji** [comment]
Taking a closer look at how this works and how this library is used, you're right. I will change the library name back to simplescreenrecorder-lib and override warnings about the package name then. I will also check if it builds for all Ubuntu versions on Launchpad. I agree that the commit is a bit huge, I didn't keep an eye on that. Let me know if I should make a new PR with smaller individual commits that explain things more detailed.

**Comment by MaartenBaert** [comment]
No, it's fine if you can just change those two things. I would have done it myself if they were separate commits, but now I don't really know what to change.

**Comment by darealshinji** [comment]
I already uploaded a new branch before I read this (https://github.com/MaartenBaert/ssr-packages/pull/2). I hope it's ok if I close this PR instead.

**Pull request closed without merging**
